// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeqGPrd5N04OUN1di2tUr9zTP7Lc7sck',
    appId: '1:115692834632:web:3a4eb7f45990bf7de66d7d',
    messagingSenderId: '115692834632',
    projectId: 'puzzle-71806852',
    authDomain: 'puzzle-71806852.firebaseapp.com',
    storageBucket: 'puzzle-71806852.firebasestorage.app',
    measurementId: 'G-62B06492R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBTcttrlR9lakzF85ubkyb95ly7U2e3ps',
    appId: '1:115692834632:android:3acb787bcdfbcebfe66d7d',
    messagingSenderId: '115692834632',
    projectId: 'puzzle-71806852',
    storageBucket: 'puzzle-71806852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ2zD6EuYjqW0aC7FNLviIMshfsj04Ffs',
    appId: '1:115692834632:ios:d4856c7dd33acb76e66d7d',
    messagingSenderId: '115692834632',
    projectId: 'puzzle-71806852',
    storageBucket: 'puzzle-71806852.firebasestorage.app',
    iosBundleId: 'com.bravetech.npuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ2zD6EuYjqW0aC7FNLviIMshfsj04Ffs',
    appId: '1:115692834632:ios:313601788b8bf571e66d7d',
    messagingSenderId: '115692834632',
    projectId: 'puzzle-71806852',
    storageBucket: 'puzzle-71806852.firebasestorage.app',
    iosBundleId: 'com.example.npuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeqGPrd5N04OUN1di2tUr9zTP7Lc7sck',
    appId: '1:115692834632:web:fb3069d2028fcf3ce66d7d',
    messagingSenderId: '115692834632',
    projectId: 'puzzle-71806852',
    authDomain: 'puzzle-71806852.firebaseapp.com',
    storageBucket: 'puzzle-71806852.firebasestorage.app',
    measurementId: 'G-CZNGH8RE0F',
  );
}
